# Generated by Django 4.0.3 on 2022-03-14 18:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_home_night_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
